[phases.setup]
nixPkgs = ["python311", "tesseract", "poppler_utils"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn core.api.entrypoint:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 60"
