#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${LIVE_CLASSES_ENV_FILE:-${ROOT_DIR}/../jee_live_classes/.env.live_classes}"

if [[ -f "${ENV_FILE}" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "${ENV_FILE}"
  set +a
fi

: "${LIVE_CLASSES_API_BASE_URL:?Set LIVE_CLASSES_API_BASE_URL}"
: "${LIVE_CLASSES_TRANSCRIPTION_WS_URL:?Set LIVE_CLASSES_TRANSCRIPTION_WS_URL}"
: "${LIVE_CLASSES_OCR_ENDPOINT:?Set LIVE_CLASSES_OCR_ENDPOINT}"
: "${LIVE_CLASSES_REQUEST_SIGNING_SECRET:?Set LIVE_CLASSES_REQUEST_SIGNING_SECRET}"

if [[ -z "${LIVE_CLASSES_SESSION_TOKEN:-}" && -z "${LIVE_CLASSES_JWT_ACCESS_TOKEN:-}" ]]; then
  echo "Set LIVE_CLASSES_SESSION_TOKEN or LIVE_CLASSES_JWT_ACCESS_TOKEN"
  exit 1
fi

flutter run \
  --dart-define=LIVE_CLASSES_ENABLE_REAL_SERVICES=true \
  --dart-define=LIVE_CLASSES_API_BASE_URL="${LIVE_CLASSES_API_BASE_URL}" \
  --dart-define=LIVE_CLASSES_TRANSCRIPTION_WS_URL="${LIVE_CLASSES_TRANSCRIPTION_WS_URL}" \
  --dart-define=LIVE_CLASSES_OCR_ENDPOINT="${LIVE_CLASSES_OCR_ENDPOINT}" \
  --dart-define=LIVE_CLASSES_REQUEST_SIGNING_SECRET="${LIVE_CLASSES_REQUEST_SIGNING_SECRET}" \
  --dart-define=LIVE_CLASSES_SESSION_TOKEN="${LIVE_CLASSES_SESSION_TOKEN:-}" \
  --dart-define=LIVE_CLASSES_JWT_ACCESS_TOKEN="${LIVE_CLASSES_JWT_ACCESS_TOKEN:-}" \
  --dart-define=LIVE_CLASSES_DEFAULT_CLASS_ID="${LIVE_CLASSES_DEFAULT_CLASS_ID:-physics_live_01}" \
  --dart-define=LIVE_CLASSES_DEFAULT_TITLE="${LIVE_CLASSES_DEFAULT_TITLE:-JEE Live Class}" \
  --dart-define=LIVE_CLASSES_DEFAULT_SUBJECT="${LIVE_CLASSES_DEFAULT_SUBJECT:-Physics}" \
  --dart-define=LIVE_CLASSES_DEFAULT_TOPIC="${LIVE_CLASSES_DEFAULT_TOPIC:-Electrostatics}" \
  --dart-define=LIVE_CLASSES_DEFAULT_TEACHER_NAME="${LIVE_CLASSES_DEFAULT_TEACHER_NAME:-Dr Sharma}" \
  --dart-define=LIVE_CLASSES_DEFAULT_START_TIME="${LIVE_CLASSES_DEFAULT_START_TIME:-6:00 PM}"
