#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${LIVE_CLASSES_ENV_FILE:-${ROOT_DIR}/.env.live_classes}"
OUT_FILE="${LIVE_CLASSES_E2E_REPORT:-${ROOT_DIR}/build/reports/live_class_real_e2e_report.json}"

if [[ -f "${ENV_FILE}" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "${ENV_FILE}"
  set +a
fi

: "${LIVE_CLASSES_API_BASE_URL:?Set LIVE_CLASSES_API_BASE_URL}"
: "${LIVE_CLASSES_TRANSCRIPTION_WS_URL:?Set LIVE_CLASSES_TRANSCRIPTION_WS_URL}"
: "${LIVE_CLASSES_OCR_ENDPOINT:?Set LIVE_CLASSES_OCR_ENDPOINT}"
: "${LIVE_CLASSES_REQUEST_SIGNING_SECRET:?Set LIVE_CLASSES_REQUEST_SIGNING_SECRET}"

if [[ -z "${LIVE_CLASSES_SESSION_TOKEN:-}" && -z "${LIVE_CLASSES_JWT_ACCESS_TOKEN:-}" ]]; then
  echo "Set LIVE_CLASSES_SESSION_TOKEN or LIVE_CLASSES_JWT_ACCESS_TOKEN"
  exit 1
fi

cd "${ROOT_DIR}"

dart run \
  -DLIVE_CLASSES_ENABLE_REAL_SERVICES=true \
  -DLIVE_CLASSES_API_BASE_URL="${LIVE_CLASSES_API_BASE_URL}" \
  -DLIVE_CLASSES_TRANSCRIPTION_WS_URL="${LIVE_CLASSES_TRANSCRIPTION_WS_URL}" \
  -DLIVE_CLASSES_OCR_ENDPOINT="${LIVE_CLASSES_OCR_ENDPOINT}" \
  -DLIVE_CLASSES_REQUEST_SIGNING_SECRET="${LIVE_CLASSES_REQUEST_SIGNING_SECRET}" \
  -DLIVE_CLASSES_SESSION_TOKEN="${LIVE_CLASSES_SESSION_TOKEN:-}" \
  -DLIVE_CLASSES_JWT_ACCESS_TOKEN="${LIVE_CLASSES_JWT_ACCESS_TOKEN:-}" \
  -DLIVE_CLASSES_CLASS_ID="${LIVE_CLASSES_CLASS_ID:-physics_live_01}" \
  -DLIVE_CLASSES_USER_ID="${LIVE_CLASSES_USER_ID:-student_01}" \
  -DLIVE_CLASSES_USER_NAME="${LIVE_CLASSES_USER_NAME:-Student}" \
  -DLIVE_CLASSES_USER_ROLE="${LIVE_CLASSES_USER_ROLE:-student}" \
  -DLIVE_CLASSES_DEFAULT_TITLE="${LIVE_CLASSES_DEFAULT_TITLE:-JEE Live Class}" \
  -DLIVE_CLASSES_DEFAULT_SUBJECT="${LIVE_CLASSES_DEFAULT_SUBJECT:-Physics}" \
  -DLIVE_CLASSES_DEFAULT_TOPIC="${LIVE_CLASSES_DEFAULT_TOPIC:-Electrostatics}" \
  -DLIVE_CLASSES_DEFAULT_TEACHER_NAME="${LIVE_CLASSES_DEFAULT_TEACHER_NAME:-Dr Sharma}" \
  -DLIVE_CLASSES_DEFAULT_START_TIME="${LIVE_CLASSES_DEFAULT_START_TIME:-6:00 PM}" \
  tool/e2e_real_classroom_audit.dart --out "${OUT_FILE}"
