const Map<String, List<String>> syllabus = <String, List<String>>{
  'Class 11': <String>[
    'Sets, Relations & Functions',
    'Complex Numbers',
    'Quadratic Equations',
    'Sequence & Series',
    'Binomial Theorem',
    'Permutations & Combinations',
    'Trigonometry',
    'Straight Line',
    'Circle',
    'Conic Sections',
    'Limits & Derivatives',
    'Statistics',
    'Probability',
    'Mathematical Reasoning',
    '3D Geometry',
    'Vector Algebra',
  ],
  'Class 12': <String>[
    'Relations & Functions',
    'Inverse Trigonometric Functions',
    'Limits, Continuity & Differentiability',
    'Applications of Derivatives',
    'Integrals',
    'Differential Equations',
    'Matrices',
    'Determinants',
    'Vector Algebra',
    '3D Geometry',
    'Linear Programming',
    'Probability',
    'Statistics',
  ],
};

const Map<String, Map<String, List<String>>> syllabusByClassAndSubject =
    <String, Map<String, List<String>>>{
      'Class 11': <String, List<String>>{
        'Physics': <String>[
          'Units and Measurements',
          'Kinematics',
          'Laws of Motion',
          'Work, Energy and Power',
          'System of Particles and Rotational Motion',
          'Gravitation',
          'Mechanical Properties of Solids',
          'Mechanical Properties of Fluids',
          'Thermal Properties of Matter',
          'Thermodynamics',
          'Kinetic Theory',
          'Oscillations',
          'Waves',
        ],
        'Chemistry': <String>[
          'Some Basic Concepts of Chemistry',
          'Structure of Atom',
          'Classification of Elements and Periodicity',
          'Chemical Bonding and Molecular Structure',
          'States of Matter',
          'Thermodynamics',
          'Equilibrium',
          'Redox Reactions',
          'Hydrogen',
          's-Block Elements',
          'p-Block Elements',
          'Organic Chemistry - Basic Principles and Techniques',
          'Hydrocarbons',
          'Environmental Chemistry',
        ],
        'Mathematics': <String>[
          'Sets, Relations and Functions',
          'Complex Numbers',
          'Quadratic Equations',
          'Sequence and Series',
          'Binomial Theorem',
          'Permutations and Combinations',
          'Trigonometry',
          'Straight Line',
          'Circle',
          'Conic Sections',
          'Limits and Derivatives',
          'Statistics',
          'Probability',
          'Mathematical Reasoning',
          '3D Geometry',
          'Vector Algebra',
        ],
        'Biology': <String>[
          'The Living World',
          'Biological Classification',
          'Plant Kingdom',
          'Animal Kingdom',
          'Morphology of Flowering Plants',
          'Anatomy of Flowering Plants',
          'Structural Organisation in Animals',
          'Cell: Structure and Function',
          'Biomolecules',
          'Cell Cycle and Cell Division',
          'Transport in Plants',
          'Mineral Nutrition',
          'Photosynthesis in Higher Plants',
          'Respiration in Plants',
          'Plant Growth and Development',
          'Digestion and Absorption',
          'Breathing and Exchange of Gases',
          'Body Fluids and Circulation',
          'Excretory Products and Elimination',
          'Locomotion and Movement',
          'Neural Control and Coordination',
          'Chemical Coordination and Integration',
        ],
      },
      'Class 12': <String, List<String>>{
        'Physics': <String>[
          'Electrostatics',
          'Current Electricity',
          'Moving Charges and Magnetism',
          'Magnetism and Matter',
          'Electromagnetic Induction',
          'Alternating Current',
          'Electromagnetic Waves',
          'Ray Optics and Optical Instruments',
          'Wave Optics',
          'Dual Nature of Radiation and Matter',
          'Atoms',
          'Nuclei',
          'Semiconductor Electronics',
        ],
        'Chemistry': <String>[
          'Solid State',
          'Solutions',
          'Electrochemistry',
          'Chemical Kinetics',
          'Surface Chemistry',
          'General Principles and Processes of Isolation of Elements',
          'p-Block Elements',
          'd and f Block Elements',
          'Coordination Compounds',
          'Haloalkanes and Haloarenes',
          'Alcohols, Phenols and Ethers',
          'Aldehydes, Ketones and Carboxylic Acids',
          'Amines',
          'Biomolecules',
          'Polymers',
          'Chemistry in Everyday Life',
        ],
        'Mathematics': <String>[
          'Relations and Functions',
          'Inverse Trigonometric Functions',
          'Limits, Continuity and Differentiability',
          'Applications of Derivatives',
          'Integrals',
          'Differential Equations',
          'Matrices',
          'Determinants',
          'Vector Algebra',
          '3D Geometry',
          'Linear Programming',
          'Probability',
          'Statistics',
        ],
        'Biology': <String>[
          'Reproduction in Organisms',
          'Sexual Reproduction in Flowering Plants',
          'Human Reproduction',
          'Reproductive Health',
          'Principles of Inheritance and Variation',
          'Molecular Basis of Inheritance',
          'Evolution',
          'Human Health and Disease',
          'Strategies for Enhancement in Food Production',
          'Microbes in Human Welfare',
          'Biotechnology: Principles and Processes',
          'Biotechnology and its Applications',
          'Organisms and Populations',
          'Ecosystem',
          'Biodiversity and Conservation',
          'Environmental Issues',
        ],
      },
    };
