export function createClassSession({
  id,
  title,
  teacherId,
  teacherName,
  activeRoomId,
  chatEnabled = true,
  meetingLocked = false,
  waitingRoomEnabled = true,
  isRecording = false,
  createdAt = new Date().toISOString(),
  activeWhiteboardUserId = null,
  whiteboardStrokes = [],
  activeRecording = null,
  recordingStatus = 'idle',
  version = 1,
}) {
  return {
    id,
    title,
    teacherId,
    teacherName,
    activeRoomId,
    chatEnabled,
    meetingLocked,
    waitingRoomEnabled,
    isRecording,
    createdAt,
    activeWhiteboardUserId,
    whiteboardStrokes,
    activeRecording,
    recordingStatus,
    version,
  };
}
