import { randomUUID } from 'node:crypto';

export function createParticipant({
  id = randomUUID(),
  userId,
  classId,
  userName,
  role = 'student',
  status = 'pending',
  breakoutRoomId = null,
  muted = false,
  cameraDisabled = false,
  whiteboardAccess = false,
  requestId = null,
  requestedAt = null,
  approvedAt = null,
  rejectedAt = null,
  presenceStatus = 'offline',
  lastSeenAt = null,
  disconnectedAt = null,
  disconnectGraceExpiresAt = null,
  version = 1,
}) {
  return {
    id,
    userId,
    classId,
    userName,
    role,
    status,
    breakoutRoomId,
    muted,
    cameraDisabled,
    whiteboardAccess,
    requestId,
    requestedAt,
    approvedAt,
    rejectedAt,
    presenceStatus,
    lastSeenAt,
    disconnectedAt,
    disconnectGraceExpiresAt,
    version,
  };
}
